### ISSUE TITLE
No option to prevent JDBC driver download

### ISSUE THREAD

**Issue by renoth** [WeltN24/gradle-sonarqube-plugin#1]
I have a project whose compile step loads the oracle jdbc driver into the classpath prior to running the sonar analysis with sonarqube.
When the sonarqube plugin downloads the JDBC driver from my sonar server and tries to load it the following error occurs:

```
10:35:16.649 INFO  - Install plugins
10:35:16.764 INFO  - Install JDBC driver
10:35:16.773 INFO  - Create JDBC datasource for jdbc:oracle:thin:@myDBserver:1521:xe
:sonarqube FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':sonarqube'.
> Unable to execute Sonar
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 9.945 secs
sealing violation: package oracle.jdbc is sealed
```

**Comment by renoth** [comment]
nevermind in think i got the wrong project, i am looking for the gradle plugin that uses the sonarqube task

**Comment by moritzzimmer** [comment]
Alright

**Comment by moritzzimmer** [comment]
By the way this @renoth: this plugin applies the default _sonar-runner_ plugin to the build script (and some useful default configuration and a preview mode task)
